services:
  proxio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1337:1337"
    depends_on:
      - proxio_redis
    networks:
      - proxio-network
      - shared-net
    env_file:
      - .env

  proxio_redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_volume:/data
    networks:
      - proxio-network

networks:
  proxio-network:
    driver: bridge
  shared-net:
    external: true
